Repository singhtaran1005/set-of-python-programs, pull requests merged in 2020-10, with the labels that each got.

#3 Update for1.py
  for1.py
Labels: hacktoberfest

#2 Update 72.py
  72.py
Labels: hacktoberfest

#7 Update week2.py
  week2.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#6 Update bubblesort.py
  bubblesort.py
Labels: hacktoberfest, hacktoberfest-accepted

#5 Update hello2.py
  hello2.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
